<script defer src="{{ BASE_URL }}resources/js/jquery-3.6.0.min.js"></script>
<script defer src="{{ BASE_URL }}resources/js/app.js"></script>
<script defer src="{{ BASE_URL }}node_modules/sweetalert/dist/sweetalert.min.js"></script>
<script defer src="{{ BASE_URL }}node_modules/pusher-js/dist/web/pusher.min.js"></script>
<script defer src="{{ BASE_URL }}node_modules/swiper/swiper-bundle.min.js"></script>
<script defer src="{{ BASE_URL }}resources/js/bundle.js"></script>
<script defer src="{{ BASE_URL }}resources/js/posts.js"></script>
<script defer src="{{ BASE_URL }}resources/js/admin.js"></script>
{{-- <script defer src="{{ BASE_URL }}resources/js/beacon.min.js"></script> --}}
{{-- <script defer src="{{ BASE_URL }}node_modules/vanilla-tilt/dist/vanilla-tilt.js"></script> --}}