<script src="{{ BASE_URL }}node_modules/tw-elements/dist/js/index.min.js"></script>
<script src="{{ BASE_URL }}node_modules/vanilla-tilt/dist/vanilla-tilt.js"></script>
<script src="{{ BASE_URL }}node_modules/sweetalert/dist/sweetalert.min.js"></script>
<script src="{{ BASE_URL }}node_modules/swiper/swiper-bundle.min.js"></script>
<script src="{{ BASE_URL }}resources/js/jquery-3.3.1.min.js"></script>
<script defer src="{{ BASE_URL }}resources/js/bundle.js"></script>
<script defer src="{{ BASE_URL }}resources/js/beacon.min.js"></script>
<script defer src="{{ BASE_URL }}resources/js/base.js"></script>
<script defer src="{{ BASE_URL }}resources/js/admin.js"></script>
